### ISSUE TITLE
dbt source does not respect `database` tag

### ISSUE THREAD

**Issue by ciejer** [TobikoData/sqlmesh#1100]
When running `sqlmesh create_external_models` on a historic dbt project which includes databases in the schema.yml, the below error is received.
Example schema.yml config:
```
sources:
  - name: util
    database: my_database
    tables:
      - name: dim_date
```

Error text:
```
snowflake.connector.errors.ProgrammingError: 002003 (02000): SQL compilation error:
Schema 'DEV_CORE.UTIL' does not exist or not authorized.
```
