### ISSUE TITLE
scaffold initialization has no input validation for dialect value

### ISSUE THREAD

**Issue by cwegener** [TobikoData/sqlmesh#1534]
Probably just a minor UX issue. It's my first day in sqlmesh. So I might not have a full understanding of all the concepts yet.

I'm following the CLI tutorial and in the very first command I mistyped `duckdb`:

`sqlmesh init duckd`

To my surprise there was no user feedback at all, neither an error nor a success message. all I see is that the exit code from `sqlmesh` is 0 and that the scaffold files got created.

And the config.yaml looks like this:

```yaml
gateways:
    local:
        connection:
            type: duckdb
            database: db.db

default_gateway: local

model_defaults:
    dialect: duckd
```

### Steps to reproduce:

1. Run `sqlmesh init duckd`

### Expected result:

- User should be warned that `duckd` is probably not going to be what the user wants.

### Actual result:

- Command silently completes with success.
