### ISSUE TITLE
Sqlmesh ui config problem on new example project

### ISSUE THREAD

**Issue by seandavi** [TobikoData/sqlmesh#1541]
Just kicking the tires on SQLmesh 0.38.0. 

```
sqlmesh init duckdb
sqlmesh ui
```

generated config.yaml
```
gateways:
    local:
        connection:
            type: duckdb
            database: db.db

default_gateway: local

model_defaults:
    dialect: duckdb
```

Quite possible I missed something, but I'm following along with the quickstart. 

<img width="1660" alt="image" src="https://github.com/TobikoData/sqlmesh/assets/92435/3a6865de-7b52-4719-ba09-8689fbd4e4a4">
