### ISSUE TITLE
Trino connection using basic auth fails

### ISSUE THREAD

**Issue by jonathandune** [TobikoData/sqlmesh#1753]
Defined a gateway as following :

```
trino:
    connection:
      type: trino
      method: basic
      user: foo
      password: bar
      host: https://trinotest
      catalog: my_catalog
    state_connection:
      type: duckdb
      database: state.db
```

When sqlmesh tries to connect, the following error is raised :

```
python-virtual-environments/sqlmeshenv/lib/python3.11/site-packages/trino/dbapi.py", line 126, in connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Connection.__init__() got an unexpected keyword argument 'password'
```

I did a bit of digging and I'm wondering whether sqlmesh is correctly using the trino python client and populating BasicAuthentication appropriately

(https://github.com/trinodb/trino-python-client/blob/f99ef245f28b4e1784a829b7935a31d0215ace4d/trino/auth.py#L109)

I see something being passed in [here](https://github.com/TobikoData/sqlmesh/blob/c715d83f505135112dd9a4c1359845d740f02dae/sqlmesh/core/config/connection.py#L1019) but I don't think it's taken into account.

Trying to run the following piece of python against the same Trino cluster with same host/user/password :

 from trino.dbapi import connect

```
conn = connect(
    host="https://trinotest",
    user="foor",
    password="bar",
    catalog="my_catalog"
)
cur = conn.cursor()
cur.execute("SELECT * FROM system.runtime.nodes")
rows = cur.fetchall()
```

gives the exact same error : Connection.__init__() got an unexpected keyword argument 'password'

But passing in BasicAuthentication like below works :

from trino.dbapi import connect
from trino.auth import BasicAuthentication

```
conn = connect(
    user="foo",
    auth=BasicAuthentication("foo", "bar"),
    ...
)
```
