### ISSUE TITLE
Test on model producing NULL date values fail with empty diff

### ISSUE THREAD

**Issue by pcasteran** [TobikoData/sqlmesh#1799]
# Issue description

Let's say we have an external model `model1` defined as follows:
```yaml
- name: dummy.model1
  columns:
    id: INT
    date: DATE
```
And a model `model2` using `model1` defined as follows:
```sql
MODEL (
  name dummy.model2,
  kind FULL,
);

SELECT
  *,
  DATE_TRUNC('month', date)::DATE AS month,
  NULL::DATE AS null_date,
FROM
  dummy.model1
```
And finally a unit test for `model2` defined as follows:
```yaml
test_null_dates:
  model: dummy.model2
  inputs:
    dummy.model1:
      rows:
        - id: 1234
          date: 2023-01-12
        - id: 9876
          date: 2023-02-10
  outputs:
    query:
      rows:
        - id: 1234
          date: 2023-01-12
          month: 2023-01-01
          null_date:
        - id: 9876
          date: 2023-02-10
          month: 2023-02-01
          null_date:
```

When running this test, I get the following error:
```bash
======================================================================
FAIL: test_null_dates (tests/test_model2.yaml)
----------------------------------------------------------------------
AssertionError: Data differs (exp: expected, act: actual)

Empty DataFrame
Columns: []
Index: []

----------------------------------------------------------------------
Ran 1 test in 0.036s

FAILED (failures=1)
```

# Analysis

In the `ModelTest.assert_equal()` method the issue seems to be related to [this line](https://github.com/TobikoData/sqlmesh/blob/573951086edf1c51366e8783e49dfb60fe24e914/sqlmesh/core/test/definition.py#L104).
This line updates the `actual` dataframe types, replace the `DATE` columns schemas.

Before this line:
```
actual.dtypes=('id', dtype('int32')) ('date', dtype('<M8[us]')) ('month', dtype('<M8[us]')) ('null_date', dtype('<M8[us]'))
```

After this lines:
```
actual.dtypes=('id', dtype('int32')) ('date', dtype('O')) ('month', dtype('O')) ('null_date', dtype('O'))
```
