### ISSUE TITLE
Incomplete test error since v0.63.0

### ISSUE THREAD

**Issue by pcasteran** [TobikoData/sqlmesh#1945]
# Issue description

Let's say we have a model defined as follows:
```sql
SELECT
  r.range::DATE AS month
FROM
  RANGE(DATE '2023-01-01', DATE '2023-04-01', INTERVAL 1 MONTH) AS r
```
And a unit test for this model defined as follows:
```yaml
test_xyz:
  model: xyz
  outputs:
    query:
      rows:
        - month: 2023-01-01
        - month: 2023-02-01
        - month: 2023-03-01
```

When running this test with v0.62.1, everything works fine.

When running it with v0.63.0, I get the following error:
```bash
Error: Incomplete test, missing input for table RANGE(CAST('2023-01-01' AS DATE), CAST('2023-04-01' AS DATE), INTERVAL '1' MONTH) at [...]
```
