### ISSUE TITLE
Views on remote files with DuckDB

### ISSUE THREAD

**Issue by soobrosa** [TobikoData/sqlmesh#2420]
This is my example `model.sql`

```
MODEL (
    name dwh.demo,
    kind VIEW
);

CALL load_aws_credentials();

SELECT
    column1,
    column2
FROM
    READ_PARQUET('s3://bucket/demo.parquet');
```

Running `sqlmesh plan dev` flies fine, view gets created.

`sqlmesh plan` gives
```
Error: Failed processing SnapshotId<"db"."dwh"."demo": 2291498964>. HTTP Error: HTTP GET error on 'https://bucket.s3.amazonaws.com/demo.parquet' (HTTP 403)
```

Sounds fair, not sure when should I do a pre `CALL load_aws_credentials();` Though I could supress this error with making a `schema.yaml`

```
- name: dwh.demo
  description: An external view
  columns:
    column1: text
    column2: text
```

What would be a ~canonical way of dealing with views on remote files? Only thing I can think of is making the views on the db before running SQLmesh then consider all of them as external tables. Neither feels right.
