### ISSUE TITLE
Self-referenced model's runtime-generated table cannot be found during tests

### ISSUE THREAD

**Issue by Giganoide01** [TobikoData/sqlmesh#2476]
While writing some tests for an incremental model, I noticed that even if I didn't use the self-referenced table in the test (therefore, assuming it doesn't exist), I still needed to add an empty input for the self-referenced table in the test file.

To illustrate this behavior, I will use the [lifetime customer revenue](https://github.com/TobikoData/sqlmesh/blob/7c28a51261061fc92e5f0b9a2f3c071feccf061f/examples/sushi/models/customer_revenue_lifetime.sql) from the sushi example.

**Environment Versions**
1. Ubuntu 22.04.3 LTS
2. Python 3.10.12
3. sqlmesh 0.89.0
4. duckdb v0.10.1 4a89d97db8

**Steps to replicate**
1. create config.yaml as:
```
gateways:
    local:
        connection:
            type: duckdb
            database: db.db

default_gateway: local

model_defaults:
    dialect: duckdb
```

2. create models/incremental_model.sql as:
```
MODEL (
  name sushi.customer_revenue_lifetime,
  kind incremental_by_time_range (
    time_column event_date,
    batch_size 1
  ),
  owner jen,
  cron '@daily',
  dialect hive,
  tags expensive,
  columns (
    customer_id INT,
    revenue DOUBLE,
    event_date DATE
  ),
  grain (customer_id, event_date),
);

WITH order_total AS (
  SELECT
    oi.order_id AS order_id,
    SUM(oi.quantity * i.price) AS total
  FROM sushi.order_items AS oi
  LEFT JOIN sushi.items AS i
    ON oi.item_id = i.id AND oi.event_date = i.event_date
  WHERE
    oi.event_date = @end_date
  GROUP BY
    oi.order_id
), incremental_total AS (
  SELECT
    o.customer_id::INT AS customer_id,
    SUM(ot.total)::DOUBLE AS revenue,
  FROM sushi.orders AS o
  LEFT JOIN order_total AS ot
    ON o.id = ot.order_id
  WHERE
    o.event_date = @end_date
  GROUP BY
    o.customer_id
), prev_total AS (
  SELECT
    crl.customer_id,
    crl.revenue
  FROM sushi.customer_revenue_lifetime AS crl
  WHERE
    crl.event_date = @end_date - INTERVAL 1 DAY
)
SELECT
  COALESCE(it.customer_id, prev_total.customer_id) AS customer_id,
  COALESCE(it.revenue, 0) + COALESCE(prev_total.revenue, 0) AS revenue,
  @end_date AS event_date
FROM incremental_total AS it
FULL OUTER JOIN prev_total AS prev_total
  ON it.customer_id = prev_total.customer_id
```

3. create tests/test_incremental_model.yaml as:
```
test_incremental_model:
  model: sushi.customer_revenue_lifetime
  inputs:
    sushi.order_items:
      rows:
        - order_id: 1
          item_id: 12
          quantity: 1
          event_date: 2000-01-02
    sushi.items:
      rows:
        - id: 12
          price: 3.99
          event_date: 2000-01-02
    sushi.orders:
      rows:
        - id: 1
          customer_id: 123
          event_date: 2000-01-02
  outputs:
    query:
      rows:
        - customer_id: 123
          revenue: 3.99
          event_date: 2000-01-02
  vars:
    end: 2000-01-02
```

4. run `sqlmesh test`. You should get an error like this:
```
duckdb.duckdb.CatalogException: Catalog Error: Table with name customer_revenue_lifetime__fixture__bla7mwyd does not exist!
Did you mean "order_items__fixture__bla7mwyd"?
LINE 1: ...l"."customer_id", "crl"."revenue" FROM "db"."sushi"."customer_revenue_lifetime...
```

5. to correct this behavior, add an empty input to sushi.customer_revenue_lifetime in tests/test_incremental_model.yaml, as shown below:
```diff
test_incremental_model:
  model: sushi.customer_revenue_lifetime
  inputs:
    sushi.order_items:
      rows:
        - order_id: 1
          item_id: 12
          quantity: 1
          event_date: 2000-01-02
    sushi.items:
      rows:
        - id: 12
          price: 3.99
          event_date: 2000-01-02
    sushi.orders:
      rows:
        - id: 1
          customer_id: 123
          event_date: 2000-01-02
+   sushi.customer_revenue_lifetime:
+     - event_date:
  outputs:
    query:
      rows:
        - customer_id: 123
          revenue: 3.99
          event_date: 2000-01-02
  vars:
    end: 2000-01-02
```

6. run `sqlmesh test` again. It should work correctly.

I expected that the test would not need an empty instance to its self-referenced table in testing scenarios where the table doesn't exist yet. Since SQLmesh ensures that self-referenced tables exist in runtime, it should also be able to read the runtime-generated table in tests.
