### ISSUE TITLE
bug report:  raise error on dbt source yaml tests field

### ISSUE THREAD

**Issue by lei0zhou** [TobikoData/sqlmesh#2538]
based on the following dbt source yaml setup, sqlmesh will raise error with `Could not render or parse jinja at '/Users/leizhou/Dev/dbt_park/models/raw-sparcs/_sources.yml'. Encountered unknown tag 'test'.`

```
---
version: 2
sources:
  - name: a
    database: abc
    schema: c
    tables:
      - name: b
        tests:
          - dbt_expectations.expect_table_columns_to_contain_set:
              column_list: ['id']
```
