### ISSUE TITLE
Enable audits in model defaults

### ISSUE THREAD

**Issue by AronsonDan** [TobikoData/sqlmesh#2567]
The scenario goes as follows:

1. table which is defined as an external source was ingested and serves as a base table
2. that table has some meta fields that i would like to drag along downstream the models
3. Would love to test all across the transformations in that model that the columns exists and to fail a plan in case it dosent

suggestion:
enable model level audits 
```yaml
model_defaults:
  dialect: snowflake
  audits:
    - assert_base_columns
```
