### ISSUE TITLE
Broken unit tests when upgrading from 0.110.0 to 0.111.0

### ISSUE THREAD

**Issue by achicoine-coveo** [TobikoData/sqlmesh#2914]
I have some unit tests that work in 0.110.0 and not in 0.111.0.

The issue seems related to changes that were made around the handling of time variables.

Here's a model and a test to reproduce.
```sql
MODEL (
  name source.serverless_task_history,
  kind INCREMENTAL_BY_TIME_RANGE (
    time_column (start_time)
  )
);

SELECT
  DATE_TRUNC('DAY', start_time)::TIMESTAMPTZ AS record_date,
  start_time::TIMESTAMPTZ,
  TASK_ID::BIGINT,
  task_name::VARCHAR,
  database_name::VARCHAR,
  schema_name::VARCHAR,
  credits_used::DOUBLE
FROM snowflake.account_usage.serverless_task_history
WHERE
  start_time BETWEEN @start_tstz AND @end_tstz
```
Test
``` yaml
test_serverless:
  model: source.serverless_task_history
  inputs:
    snowflake.account_usage.serverless_task_history:
      query: |
        select
        '2024-06-01 01:05:00 +0000'::timestamptz as start_time,
        null as task_id,
        null as task_name,
        null as database_name,
        null as schema_name,
        null as credits_used
  outputs:
    partial: true
    query:
      partial: true
      rows:
      - start_time: 2024-06-01 01:05:00 +0000
        record_date: 2024-06-01 00:00:00 +0000

  vars:
    start_tstz: 2024-06-01 00:00:00+0000
    end_tstz: 2024-06-02 00:00:00+0000
```

Running it with sqlmesh 0.110.0
<img width="208" alt="image" src="https://github.com/user-attachments/assets/a56fc169-0616-46db-b77a-642db53fbc5c">

Running it with sqlmesh 0.111.0
<img width="1325" alt="image" src="https://github.com/user-attachments/assets/361a996d-1e6a-494b-a1e4-b672bfefa19a">

This seems to come from a different issue with partial where it will give this error when no rows make it through the filter.

Let's bypass the partial issue by adding the columns to the outputs.

The test becomes this:
``` yaml
test_serverless:
  model: source.serverless_task_history
  inputs:
    snowflake.account_usage.serverless_task_history:
      query: |
        select
        '2024-06-01 01:05:00 +0000'::timestamptz as start_time,
        null as task_id,
        null as task_name,
        null as database_name,
        null as schema_name,
        null as credits_used
  outputs:
    partial: true
    query:
      partial: true
      rows:
      - start_time: 2024-06-01 01:05:00 +0000
        record_date: 2024-06-01 00:00:00 +0000
        task_id: null
        task_name: null
        database_name: null
        schema_name: null
        credits_used: null


  vars:
    start_tstz: 2024-06-01 00:00:00+0000
    end_tstz: 2024-06-02 00:00:00+0000
```

I get this error about missing rows:
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/28bd745c-a9f0-4a77-ae93-b4bfde7aed6d">

Go back to sqlmesh 0.110.0
<img width="606" alt="image" src="https://github.com/user-attachments/assets/ab744b89-c72b-4790-bdc0-d81b33585632">
