### ISSUE TITLE
UX Feat: Enable a config to force a prompt to prevent people from naively running `sqlmesh plan` directly against prod

### ISSUE THREAD

**Issue by sungchun12** [TobikoData/sqlmesh#3119]
This has come up in several conversations where people want to prevent their data engineers from accidentally running `sqlmesh plan` against prod. This is not meant to be a solve for true permissions, but it does inject friction to prevent someone from accidentally applying a plan to prod when they intended to run against a dev environment.

```yaml
gateways:
    tobiko_cloud: # this will use the config in tcloud.yaml for state_connection
        connection:
            type: bigquery
            method: service-account-json
            concurrent_tasks: 5
            register_comments: true
            keyfile_json: {{ env_var('GOOGLE_SQLMESH_CREDENTIALS') }}
            project: sqlmesh-public-demo

default_gateway: tobiko_cloud

model_defaults:
    dialect: bigquery

plan_prod_prompt: enabled # something like this
```

After someone enters `1`, it will then run the normal plan operations.
```shell
(.venv) ➜  tobiko-cloud-demo git:(demo) ✗ sqlmesh plan
======================================================================
Are you sure you want to apply this plan to prod? 
----------------------------------------------------------------------
Enter 1 for yes: 
```
