### ISSUE TITLE
Lower casing database name when deploying models to MSSQL

### ISSUE THREAD

**Issue by lanekatris** [TobikoData/sqlmesh#3289]
Hello, for the given `config.yaml` that talks to Microsoft SQL (using windows authentication, which works fine):
```yaml
gateways:
  local:
    connection:
      type: mssql
      host: my-sql-server
      database: Financial
    test_connection:
      type: duckdb
      database: db2.db
    state_connection:
      type: duckdb
      database: db2.db

default_gateway: local

model_defaults:
  dialect: tsql
  start: 2024-10-22
```

When running `sqlmesh plan`, the database name is now lower cased "financial":
![image](https://github.com/user-attachments/assets/5e681b4f-821a-4cb3-9447-5305dd4d5cb4)

After choosing yes it cannot find the database:

> pymssql.exceptions.OperationalError: (911, b"Database 'financial' does not exist. Make sure that the name is entered correctly.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")

![image](https://github.com/user-attachments/assets/15d7c1ce-4add-4022-9e2a-f7580acca009)

I did try pydantic v1 and v2. I'm using sqlmesh version 0.129.0 and pydantic 2.9.2.

I apologize if this is user error, I was wondering if there is a way to control casing? `sqlmesh` is an exciting product, thanks for your time!
