### ISSUE TITLE
GitHub CI/CD Bot: Add option to run a data diff for models changed and those impacted downstream

### ISSUE THREAD

**Issue by sungchun12** [TobikoData/sqlmesh#3297]
**Problem**: A user makes changes to their models and they see how code changed, models impacted, and unit tests run. However, it's still opaque as to how exactly data has changed. It's hard to review the PR with confidence without running ad hoc queries to know the differences between dev and prod.

**Solution**: Add a config option in addition to a tabbed output in the GitHub Action formatted output that shows the data diff stats automatically and have it automatically diff by picking up the `grain` to run the data diff. 

Example config:
```yaml
cicd_bot:
    type: github
    merge_method: squash
    enable_deploy_command: true
    enable_table_diff: true # this is the one
    auto_categorize_changes:
      external: full
      python: full
      sql: full
      seed: full
```

**Note**: probably want to prevent showing sample data and give a warning or error to the user that this is not allowed in the official ci/cd bot for security reasons.
