### ISSUE TITLE
Missing data in incremental models by time range

### ISSUE THREAD

**Issue by manucalop** [TobikoData/sqlmesh#3433]
Hi! I'm getting less rows than expected when doing incremental models in BigQuery. Here is a reproducible example:

1. Take the [dataset thelook_eccommerce](https://console.cloud.google.com/marketplace/product/bigquery-public-data/thelook-ecommerce) and make a copy of `events` table to a dataset called ecommerce_demo.

2. Initialize a new SQLMesh project with the following `config.yaml`:

    ```yaml
    gateways:
      local:
        connection:
          type: duckdb
          database: local.db
    
      bigquery:
        state_connection:
          type: duckdb
          database: state.db
        connection:
          type: bigquery
          project: your_gcloud_project
          location: europe-west1
    
    default_gateway: bigquery
    
    model_defaults:
      dialect: bigquery
      start: 2024-11-01
    ```

3. Create the following model:

    ```sql
    MODEL (
        name ecommerce_demo_silver.events_test,
        kind INCREMENTAL_BY_TIME_RANGE (
          time_column (created_at, '%Y-%m-%d %H:%i:%s %Z'),
        ),
        cron '@daily',
        grain (event_id),
        partitioned_by TIMESTAMP_TRUNC(created_at, DAY),
    );
    
    SELECT *
    FROM ecommerce_demo.events
    WHERE created_at BETWEEN @start_ds and @end_ds
    ```

4. Check that it fails to bring the same number of rows:

    ```sql
    with counts_web_events as (
      select 
      count(distinct id) as n_web_events
    from ecommerce_demo_silver.events_test
    )
    , counts_events as (
      select 
      count(distinct id) as n_events
    from ecommerce_demo.events
    where date(created_at) >= '2024-11-01'
    )
    select *
    from counts_web_events, counts_events
    where n_web_events <> n_events
    -- 117477, 124223
    ```
    
    Thanks!
