### ISSUE TITLE
Systematically add the gateway info to table models in `external_tables.yaml`

### ISSUE THREAD

**Issue by esciara** [TobikoData/sqlmesh#3443]
Given the context where we have two gateways with the `config.yaml` as follows

```yaml
gateways:
  local:
    connection:
      type: duckdb
      database: my_transfo.db
  bigquery:
    connection:
      type: bigquery
      project: my-project
      location: europe-west1
    state_connection:
      type: duckdb
      database: bigquery_state.duckdb

default_gateway: duckdb

model_defaults:
  dialect: bigquery
  start: 2024-10-30
```

Currently when creating external models through `sqlmesh create_external_models`, gateway information is not added to the models. Hence the information in the `external_models.yaml` file looks something like this:

```yaml
- name: '`my_transfo`.`dataset_or_schema`.`table_name`'
  columns:
    col_1: STRING
    col_2: STRING
```

When creating the  external models for the `bigquery` gateway through `sqlmesh --gateway bigquery create_external_models`, the external models are changed like this:

```yaml
- name: '`my_transfo`.`dataset_or_schema`.`table_name`'
  columns:
    col_1: STRING
    col_2: STRING
- name: '`my-project`.`dataset_or_schema`.`table_name`'
  columns:
    col_1: STRING
    col_2: STRING
  gateway: bigquery
```

Say I change my default gateway to `bigquery` in `config.yaml`:

```yaml
default_gateway: bigquery
```

If then I add a new column to the table, then it is not the table defined for the `bigquery` gateway that is changed, but the one for the `default` gateway. Hence the file is changed like this:

```yaml
- name: '`my_transfo`.`dataset_or_schema`.`table_name`'
  columns:
    col_1: STRING
    col_2: STRING
    col_3: STRING
- name: '`my-project`.`dataset_or_schema`.`table_name`'
  columns:
    col_1: STRING
    col_2: STRING
  gateway: bigquery
```

But when I do a `sqlmesh plan`, even though the default gateway has been changed to `bigquery`, it is not the default definition of the external table that is used, but the one labelled for the gateway `bigquery`. Hence `sqlmesh` throws an error saying it does not find `col_3`.

The simple solution to this would be to add the gateway information to all external models, regardless of whether it is the default gateway or not.
