### ISSUE TITLE
`sqlmesh init <database>` should dynamically generate a specific template config

### ISSUE THREAD

**Issue by sungchun12** [TobikoData/sqlmesh#3459]
When I initialize a new sqlmesh project, I want to see template configs beyond the standard duckdb one. It should be specific to the database specified and should be commented out yaml lines. It makes it easier as I have one less browser tab to open in docs to update the config as needed. 

[Internal slack thread](https://tobikodata.slack.com/archives/C04DTU8RF4J/p1733159755768409)

```shell
sqlmesh init bigquery
bat config.yaml 
───────┬───────────────────────────────────────────────────────────────────────────
       │ File: config.yaml
───────┼───────────────────────────────────────────────────────────────────────────
   1   │ gateways:
   2   │   local:
   3   │     connection:
   4   │       type: duckdb
   5   │       database: db.db
   6   │ 
   7   │ default_gateway: local
   8   │ 
   9   │ model_defaults:
  10   │   dialect: bigquery
  11   │   start: 2024-12-01
```

Future Output

```yaml
  gateways:
      local:
          type: bigquery
          method: service-account-json
          concurrent_tasks: 5
          register_comments: true
          keyfile_json: {{ env_var('GOOGLE_SQLMESH_CREDENTIALS') }} # it'll be nice to even include env var placeholders as I've seen users accidentally include plain text passwords in their configs
          project: your-project

  default_gateway: local

  model_defaults:
      dialect: bigquery

```
