### ISSUE TITLE
Danish characters in SQLMesh Python model

### ISSUE THREAD

**Issue by SilasFriby** [TobikoData/sqlmesh#3475]
Hi,

I am considering whether or not to use SQLMesh for my upcomming large data transformations project. However, I am encountering some issues in my initial testing of SQLMesh that I hope you can help me with.

The issue evolves aroud the Danish characters Æ, Ø and Å. When I use the Danish characters in a SQLMesh SQL model (see sql_test_model.sql below) everything works out fine. But, when using a SQLMesh Python model (see python_test_model.py below) the danish letters are not correctly displayed in the resulting sql table. I have also added my config.yaml below. 

Additional info: I tried playing around with different column types in the Python model, when e.g using 'nvarchar' instead of 'string' the resulting sql table suddenly had chinese characters..

I hope you can help me with this small but very annoying issue.

Best regards,
Silas Friby

**sql_test_model.sql**

```sql
MODEL (
    name 'sql_test_table',
    kind FULL,
    columns (
        danish NVARCHAR(50) 
    )
);

SELECT
    *
FROM (VALUES
    (N'æble'),
    (N'øl'),
    (N'ånd')
) AS data(danish);
```

**python_test_model.py**

```python
# ====================================================
# Imports
# ====================================================

# Type hints
from typing import Any

# Data manipulation
import pandas as pd

# SQLMesh
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName

# Date and time
from datetime import datetime


# ====================================================
# Test Table
# ====================================================

@model(
    name="python_test_table",
    kind=dict(name=ModelKindName.FULL),
    description="Raw dimension table for contact areas (KontaktOmraade) from DMS",
    columns={
        "danish": "string",
    },
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: Any,
) -> pd.DataFrame:
    """
    Loads contact area data from DMS system.
    
    Args:
        context: SQLMesh execution context
        start: Start of the execution window
        end: End of the execution window
        execution_time: Time of execution
        **kwargs: Additional arguments
        
    Returns:
        DataFrame containing contact area information
    """
    
    # Create data with danish words containing æøå 
    data = {
        "danish": ["æble", "øl", "ånd"]
    }

    # Create DataFrame
    df = pd.DataFrame(data)

    return df

```

**config.yaml**

```yaml
project: sql_mesh_testing

model_defaults:
  dialect: tsql

default_gateway: development

gateways:
  development:
    connection:
      type: mssql
      host: "{{ env_var('SQL05_SERVER') }}"  
      user: "{{ env_var('SQL05_USERNAME') }}"  
      password: "{{ env_var('SQL05_PASSWORD') }}" 
      database: "{{ env_var('SQL05_DATABASE') }}" 

```
