### ISSUE TITLE
Support freezing current_timestamp with execution_time when testing in BigQuery

### ISSUE THREAD

**Issue by serkef** [TobikoData/sqlmesh#3601]
# What's the problem
freezing `CURRENT_TIMESTAMP` when testing in bq does not work as expected.
It works as expected on duckdb.

# What happens
On bq, the query tries to do `CAST('2024-01-01 00:00:00+00:00' AS DATETIME)` which is illegal. it should be `CAST('2024-01-01' AS ..)` or `CAST'(2024-01-01 00:00:00 AS ..)'`

# How to reproduce

model.sql
```sql
MODEL (
  name sqlmesh_poc.example_datetime,
  kind FULL,
);

SELECT
  user_id,
  TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), signup_timestamp, DAY) = 0 AS is_d0
FROM
  sqlmesh_poc.source_table
```

test.yaml
```
test_example_datetime:
  model: example_datetime
  inputs:
    sqlmesh_poc.source_table:
      columns:
        user_id: string
        signup_timestamp: DATETIME
      rows:
        - user_id: user_1
          signup_timestamp: 2024-01-01
        - user_id: user_2
          signup_timestamp: 2023-01-01
  outputs:
    query:
    - user_id: user_1
      is_d0: True
    - user_id: user_2
      is_d0: False
  vars:
    execution_time: 2024-01-01
```
