### ISSUE TITLE
Support `with ordinal` in duckdb

### ISSUE THREAD

**Issue by serkef** [TobikoData/sqlmesh#3671]
Having a model with the syntax `unnest ... with offset ... as ...` (works in bq and I think in postgres as well) tests are breaking with a duckdb error ```Not implemented Error: WITH ORDINALITY not implemented.``` 
Can I overcome this? 
Some relevant info I found: [stackoverflow](https://stackoverflow.com/questions/78635682/duckdb-support-for-postgres-function-with-ordinality).
It seems there is not a native duckdb way to do this. 

How to reproduce: The following works with BQ engine, but fails with DuckDB
model:
```sql
MODEL (
  name sqlmesh_poc.example_unnest_offset,
  kind FULL,
);

SELECT
  number,
  number_offset
FROM
  sqlmesh_poc.source_table,
  UNNEST(some_numbers) AS number WITH OFFSET AS number_offset
```

test:
```yaml
test_example_unnest_offset:
  model: sqlmesh_poc.example_unnest_offset
  inputs:
    sqlmesh_poc.source_table:
      columns:
        some_numbers: ARRAY<INT64>
      rows:
      - some_numbers: [0, 5]
      - some_numbers: [2, 3]
  outputs:
    query:
    - number: 0
      number_offset: 0
    - number: 5
      number_offset: 1
    - number: 2
      number_offset: 0
    - number: 3
      number_offset: 1
```
