### ISSUE TITLE
Support for versioning models (similar to DBT model version)

### ISSUE THREAD

**Issue by destefanoadonis** [TobikoData/sqlmesh#3785]
As a person/team managing a project that builds models used by other teams, I want to ability to version my models in a way that allows me to release new versions. 

DBT's solution for this is model versions. Basically a model sql file would have the following convention `my_model_v{k}.sql`. That would be referenced in a schema.yaml associated with the model (ex. my_model.yaml). In that you could manage details such as the columns, expectations/quality checks, and reference the prod version of the model. 

Consumers downstream would reference the table without the version `my_model` and you could control the release at the config level.

https://docs.getdbt.com/docs/collaborate/govern/model-versions

```
models:
  - name: dim_customers
    latest_version: 1
    
    # declare the versions, and fully specify them
    versions:
      - v: 2
        config:
          materialized: table
          contract: {enforced: true}
        columns:
          - name: customer_id
            description: This is the primary key
            data_type: int
          # no country_name column
      
      - v: 1
        config:
          materialized: table
          contract: {enforced: true}
        columns:
          - name: customer_id
            description: This is the primary key
            data_type: int
          - name: country_name
            description: Where this customer lives
            data_type: varchar
```
