### ISSUE TITLE
Postgres connection parameter 'role passed verbatim

### ISSUE THREAD

**Issue by simon-pactum** [TobikoData/sqlmesh#3814]
When configuring a `role` that's not in itself a valid identifier for a postgres connection it's not escaped/quoted when doing `SET ROLE` so ends up erroring:

```
# postgres.log
db=mydb,user=my-user ERROR:  syntax error at or near "-" at character 16
db=mydb,user=my-userSTATEMENT:  SET ROLE actual-role
```

```yaml
# config.yaml
default_gateway: example

gateway:
  example:
    connection:
      type: postgres
      host: 127.0.0.1
      user: "my-user"
      password: "password"
      port: 5432
      database: mydb
      role: "actual-role"
```

```sql
-- Reproduce db setup with psql
CREATE DATABASE mydb;
\c mydb
CREATE ROLE "actual-role";
GRANT pg_read_all_data, pg_write_all_data TO "actual-role";
CREATE ROLE "my-user" WITH LOGIN ENCRYPTED PASSWORD 'password';
GRANT "actual-role" TO "my-user";
```

### Workaround

Quote it before passing in e.g.

```
      role: '"actual-role"'
```

But that doesn't feel good
