### ISSUE TITLE
Add var support for dbt yaml files

### ISSUE THREAD

**Issue by georgesittas** [TobikoData/sqlmesh#398]
We can have dbt `var` references in YAML files too, besides model files. For example:

```yaml
sources:
  - name: my_source
    tables:
      - name: my_source_table
        config:
          enabled: “{{ var(‘my_source_table_enabled’, false) }}”
```

Here, we expect `my_source_table_enabled` to be a `var` defined in the `dbt_project.yml` file.
