### ISSUE TITLE
Add support for package-scoped dbt vars

### ISSUE THREAD

**Issue by georgesittas** [TobikoData/sqlmesh#399]
We can have package-scoped definition of dbt `var`s in `dbt_project.yml`. For example:

```yaml
name: my_dbt_project
version: 1.0.0

config-version: 2

vars:
  # The `start_date` variable will be accessible in all resources (i.e. global var)
  start_date: '2016-06-01'

  # The `platforms` variable is only accessible to resources in the my_dbt_project project
  my_dbt_project:
    platforms: ['web', 'mobile']

  # The `app_ids` variable is only accessible to resources in the snowplow package
  snowplow:
    app_ids: ['marketing', 'app', 'landing-page']

models:
    ...
```

Source: https://docs.getdbt.com/docs/build/project-variables
