### ISSUE TITLE
can't find catalog that is not the default catalog

### ISSUE THREAD

**Issue by artesarh** [TobikoData/sqlmesh#4088]
I have this issue where:

1. I have 2 duckdb databases defined as below, whichever one is the default catalog is detected when running evaluate or plan, but the other is not found.
2. In test mode - running "sqlmesh test" I can successfully connect and query both gateways referenced via the gateway key.
3. when I swap the default gateway then whichever is the default works

```
gateways:
  data2:
    connection:
      type: duckdb
      database: /data/db/database1.duckdb
  data1:
    connection:
      type: duckdb
      database: /data/db/database2.duckdb

default_gateway: data1 

model_defaults:
  dialect: duckdb
```

running:
```
sqlmesh evaluate main.mymodel1
```

```
    self.cursor.execute(sql, **kwargs)
duckdb.duckdb.BinderException: Binder Error: Catalog "data2" does not exist!
```

I worked round this by manually attaching whichever database was not the default to mymodel1 then mymodel2 and so on. but this seems to defeat the point of the gateways.
