### ISSUE TITLE
SQLMesh[databricks] to_timesatmp function inserts unnecessary POWER fn. when rendered

### ISSUE THREAD

**Issue by lafirm** [TobikoData/sqlmesh#4226]
Using sqlmesh[databricks]==0.141.1 version with the below config which unnecessarily inserts `"  / POWER(10, "` in the rendered sql in `TO_TIMESTAMP` function, is it fixed in newer versions (which I can't unfortunaley use due to https://github.com/TobikoData/sqlmesh/issues/4225?

```
gateways:
  databricks:
    connection:
      type: databricks
      server_hostname: <redacted>
      http_path: <redacted>
      access_token: <redacted>
      catalog: <redacted>
    state_connection:
      type: duckdb
      database: databricks_state.db

default_gateway: databricks

model_defaults:
  dialect: duckdb
  start: 2025-04-22

```

```sql
MODEL (
  name sqlmesh_example.example_model,
  kind FULL,
  cron '@daily',
  grain id,
);

SELECT
  1 AS id,
  TO_TIMESTAMP('20250423000000', 'yyyyMMddHHss') AS ingest_datetime
```

Which is rendered as below and gives null value as output

```sql
SELECT                                                                                                             
  1 AS "id",                                                                                                       
  TO_TIMESTAMP('20250423000000' / POWER(10, 'yyyyMMddHHss')) AS "ingest_datetime" 
```

Output:
| id | ingest_datetime |
|----|-----------------|
| 1  | null            |
