### ISSUE TITLE
Bug: DataFrame Comparison Fails When None Present in Output Column

### ISSUE THREAD

**Issue by nickmuoh** [TobikoData/sqlmesh#4400]
When running SQLMesh unit tests, if the expected and actual DataFrames contain None in a date column (e.g., churn_date), the test fails with a pandas assert_frame_equal error—even though the values appear identical. This only happens when the first few rows of the column are None. If the first few rows are non-null, the test passes.

Example SQLMesh Model (`models/simple_subscription_model.sql`)
```sql
MODEL (
  name example.simple_subscription_model,
  kind FULL
);

SELECT
  'user-1' AS customer_id,
  '2023-01-25' AS observed_date,
  NULL AS churn_date,
  FALSE AS is_churn
UNION ALL
SELECT
  'user-2' AS customer_id,
  '2023-01-25' AS observed_date,
  '2023-06-15' AS churn_date,
  TRUE AS is_churn
```

Example Test (`tests/test_simple_subscription_model.yaml`)
```yaml
test_simple_subscription_model:
  model: example.simple_subscription_model
  description: "Test for None/null handling in churn_date"
  inputs: {}
  outputs:
    query:
      rows:
        - customer_id: "user-1"
          observed_date: "2023-01-25"
          churn_date: null
          is_churn: false
        - customer_id: "user-2"
          observed_date: "2023-01-25"
          churn_date: "2023-06-15"
          is_churn: true
```

## Error Output
from `sqlmesh/core/test/definition.py` in 
```python
pd.testing.assert_frame_equal(
    expected,
    actual,
    check_dtype=False,
    check_datetimelike_compat=True,
    check_like=True,
)
```

```python
AssertionError: DataFrame.iloc[:, 2] (column name="churn_date") are different

DataFrame.iloc[:, 2] (column name="churn_date") values are different (50.0 %)
[index]: [0, 1]
[left]:  [None, '2023-06-15']
[right]: [None, '2023-06-15']
At positional index 0, first diff: '2023-06-15' != '2023-06-15'
```

* The values in the churn_date column look identical (None in both), but pandas considers them different.
* This is likely due to pandas treating None and NaN or other null representations differently in object columns, especially when the first value is None.

## Suggested Fix
In the SQLMesh test runner (`sqlmesh/core/test/definition.py`, `ModelTest.assert_equal`), ensure that columns with possible None/NaN values are normalized to a common type (e.g., string or pandas NA) before calling `assert_frame_equal`.
