### ISSUE TITLE
mono repo -> multi repos throwing Error: Duplicate key ...in UniqueKeyDict<models>

### ISSUE THREAD

**Issue by lafirm** [TobikoData/sqlmesh#4497]
We initially used a monorepo setup but recently decided to switch to a multi-repo structure. To support this, we introduced the project variable in config.yaml as described in the [SQLMesh multi-repo guide](https://sqlmesh.readthedocs.io/en/latest/guides/multi_repo/). However, adding the project variable to our existing repository is causing the following error:

> Error: Duplicate key '"iceberg"."schema"."table_1"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.

Is there an easy or recommended way to migrate from a monorepo to a multi-repo setup? Thank you!

**Comment by tobymao** [comment]
can you provide a fully reproducible minimal example?

**Comment by lafirm** [comment]
> can you provide a fully reproducible minimal example?

sure, the below steps will produce the error.

`sqlmesh init duckdb`

`sqlmesh plan`

and apply the plan. Once done, introduce the project variable in the config.yaml like this,

```
project: demo

gateways:
  duckdb:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: duckdb
      database: db.db
      # concurrent_tasks: 1
      # register_comments: True
      # pre_ping: False
      # pretty_sql: False
      # catalogs: 
      # extensions: 
      # connector_config: 
      # token: 


default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2025-05-21
```


then again run

`sqlmesh plan`

which will throw the below error,

> Error: Duplicate key '"db"."sqlmesh_example"."incremental_model"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.

Note:
Model name in the error output is different every time and the error occurs even with -p arg in the command, refer below for the sequence of tries and errors in th cli

> .venv(bot)@K6W46PHGL7 sqlmesh-repo % sqlmesh plan       
> Error: Duplicate key '"db"."sqlmesh_example"."incremental_model"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.
> .venv(bot)@K6W46PHGL7 sqlmesh-repo % sqlmesh plan       
> Error: Duplicate key '"db"."sqlmesh_example"."full_model"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.
> .venv(bot)@K6W46PHGL7 sqlmesh-repo % sqlmesh -p /Users/bot/projects/sqlmesh-repo plan           
> Error: Duplicate key '"db"."sqlmesh_example"."seed_model"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.
> .venv(bot)@K6W46PHGL7 sqlmesh-repo % sqlmesh -p /Users/bot/projects/sqlmesh-repo plan
> Error: Duplicate key '"db"."sqlmesh_example"."incremental_model"' found in UniqueKeyDict<models>. Call dict.update(...) if this is intentional.
> .venv(bot)@K6W46PHGL7 sqlmesh-repo %
> 
> 
>
