### ISSUE TITLE
dbt: BigQueryConfig - extra fields not permitted

### ISSUE THREAD

**Issue by awoehrl** [TobikoData/sqlmesh#717]
Hi!

I'm trying to use a dbt project as base, but it seems sqlmesh doesn't like our profiles.yml file:

```
Error: 5 validation errors for BigQueryConfig
job_creation_timeout_seconds
  extra fields not permitted (type=value_error.extra)
job_execution_timeout_seconds
  extra fields not permitted (type=value_error.extra)
job_retries
  extra fields not permitted (type=value_error.extra)
job_retry_deadline_seconds
  extra fields not permitted (type=value_error.extra)
priority
  extra fields not permitted (type=value_error.extra)
```

This is an excerpt of our profiles.yml:

```
dwh:
  target: dev-dev
  outputs:
    dev-dev:
      type: bigquery
      method: oauth
      project: dwh-project
      dataset: dev
      location: EU
      threads: 8
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 5000
      job_retries: 1
      job_retry_deadline_seconds: 1200
      priority: interactive
```

Appreciate your help!
