### ISSUE TITLE
Connection name potentially hardcoded to duckdb in quickstart

### ISSUE THREAD

**Issue by jared-rimmer** [TobikoData/sqlmesh#754]
I went through the [quick start](https://sqlmesh.readthedocs.io/en/stable/quick_start/) but instead of using duckdb I updated the connection config to a local Postgres Docker container.

Which looks like this:

```
connections:
    local:
        host: localhost
        user: postgres
        password: postgres
        port: 5432
        database: postgres
        type: postgres

default_connection: local
```
As I went through the quick start and typed in commands in the terminal it always showed:

```
======================================================================
Successfully Ran 1 tests against duckdb
----------------------------------------------------------------------
```
I can't find any local reference to duckdb so I am assuming it is harcoded somewhere?
